# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore source\c#\EmailDup.NET8.csproj
    - name: Build
      run: dotnet build source\c#\EmailDup.NET8.csproj --no-restore
#    - name: Test
#      run: dotnet test --no-build --verbosity normal

